feat(common-scripts): support signing with phantom on solana
nervosnetwork/lumos pull request #663
Opened 2024-04-07 08:16 UTC by homura

# Description

This PR supports signing with Phantom on Solana  

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] unit test
- [ ] manually test

2024-04-22 01:58 UTC, 15168316096 requested changes

2024-04-22 01:58 UTC, 15168316096 commented on examples/omni-lock-solana/index.tsx
> +  if (!solana) return <div>UniSat is not installed</div>;
use wallet is phantom is not unisat

2024-04-22 01:58 UTC, 15168316096 commented on examples/omni-lock-solana/index.tsx
> +  if (!solanaAddr) return <button onClick={connectToWallet}>Connect to UniSat</button>;
use wallet is phantom is not unisat

2024-04-22 01:58 UTC, 15168316096 commented on examples/omni-lock-solana/README.md
> +# Lumos Works with UniSat
here sol just works with phantom wallet not unisat

2024-04-22 01:58 UTC, 15168316096 commented on examples/omni-lock-solana/README.md
> +- [MetaMask](https://unisat.io/) - A crypto wallet for Bitcoin
The description here is wrong. You have to use sol and phantom. There may be similar errors in the description of the previous example.

2024-04-22 01:59 UTC, homura commented on examples/omni-lock-solana/index.tsx
> +  if (!solana) return <div>UniSat is not installed</div>;
I'll fix the issue

2024-04-24 14:56 UTC, homura commented
@15168316096 hi, i've corrected the description

2024-04-26 07:50 UTC, homura commented
Hi @Keith-CY ,this pr is ready for review, please check it

2024-04-28 05:10 UTC, Keith-CY commented on examples/omni-lock-solana/README.md
> +cd examples/omni-lock-
Should `cd examples/omni-lock-` be completed?

2024-04-28 05:10 UTC, Keith-CY commented on packages/common-scripts/src/omnilock.ts
> +const ED25519_SIGNATURE_PLACEHOLDER_LENGTH =
It can be set `96` directly with a comment of `32 bytes for signature and 16 bytes for public key`

2024-04-28 05:10 UTC, Keith-CY commented on packages/common-scripts/src/omnilock.ts
> +            ckbHash(bs58Decode(omnilockInfo.auth.content)).slice(0, 42),
`42` is a magic number

2024-04-28 05:10 UTC, Keith-CY commented on packages/common-scripts/src/omnilock.ts
> +        : SECP256K1_SIGNATURE_PLACEHOLDER_LENGTH;
It's easy to be a bug if it treats `SECP256K1_SIGNATURE_PlACEHOLDER_LENGTH` as a fallback, should be exactly matched or throw an error when none is matched.

2024-04-28 09:41 UTC, homura commented
@Keith-CY, I've added a new ESLint rule `@typescript-eslint/no-magic-numbers` for staged files to avoid magic numbers

2024-04-28 09:47 UTC, Keith-CY approved these changes

2024-04-28 10:10 UTC, merged